### ISSUE TITLE
Python/PyObjC program failed to start.

### ISSUE THREAD

**Issue by jpscharf** [kornelski/ImageAlpha#40]
I am unable to get ImageAlpha to start, here is what I get when running from the CLI:
```
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    import ImageAlphaDocument
  File "/Applications/ImageAlpha.app/Contents/Resources/ImageAlphaDocument.py", line 7, in <module>
    import IAImageView
  File "/Applications/ImageAlpha.app/Contents/Resources/IAImageView.py", line 11, in <module>
    class IAImageView(NSView):
objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector _setZoom of IAImageView at 0x1107d2ed0>
```

**Comment by kornelski** [comment]
This app needs a rewrite in something better than Python + PyObjC, and I don't have time to do it :(

Until then, try:

https://imageoptim.com/online

or enable Lossy mode in ImageOptim Mac app.

They don't have a preview or as many options, but they have good defaults that make it mostly unnecessary.
